default: &default
  adapter: postgresql
  host: <%=ENV['host']%>
  timeout: <%=ENV['timeout']%>
  schema_search_path: <%=ENV['schema_search_path']%>

development:
  adapter: postgresql
  host: <%=ENV['host']%>
  timeout: <%=ENV['timeout']%>
  schema_search_path: <%=ENV['schema_search_path']%>
  database: <%=ENV['database']%>
  username: <%=ENV['username']%>
  password: <%=ENV['password']%>